### ISSUE TITLE
Its dead Jim!

### ISSUE THREAD

**Issue by MauriceButler** [polyhack/nodejsau#38]
http://nodejs.org.au is not working. Some with the access can give it a kick? Ping @someoneweird @rvagg

**Comment by SomeoneWeird** [comment]
No clue where it's hosted, that would be @rvagg's domain.

**Comment by rvagg** [comment]
sorry sorry, disk filled up

**Comment by MauriceButler** [comment]
Thanks @rvagg 

I know you are a busy man is this something you would like to hand off? 

I would be happy to look after it if you want.

**Comment by SomeoneWeird** [comment]
+1 can help too if needed

**Comment by rvagg** [comment]
I would .. but I've started putting some personal & family sites on that server too, I'm just unresponsive atm cause Node v4 is kind of sucking all my time! that'll be done soon.

**Comment by MauriceButler** [comment]
Ok. Let me know if I can help out. On any front.

**Comment by SomeoneWeird** [comment]
I'd be happy to host it elsewhere if needed

**Comment by MauriceButler** [comment]
@rvagg I dont want to add to your workload buuuuut, its dead again.

Different but dead.

Again between @SomeoneWeird and myself we are more than happy to help out with this when you get the headspace to divide it up.

**Comment by rvagg** [comment]
I didn't do anything but it's up now, perhaps just a blip? I didn't get a down notification from statuscake but then again I didn't get one for nodei.co either which went down ... hmmm

if someone wants to host it on another host then I'll happily point the DNS there

**Comment by rvagg** [comment]
@MauriceButler @SomeoneWeird I've been getting the server organised, it's hosting a bunch of separate stuff, and one of the things I've done is setup [github-webhook](https://github.com/rvagg/github-webhook) for nodejsau. So now, when commits are pushed to master here, they _should_ be automatically deployed to the site. The delay should be less than a minute for it to all happen (clone, rebuild, deploy, restart), although the site startup takes a while cause it has to fetch data from github.

**Comment by SomeoneWeird** [comment]
:ok_hand:

**Comment by MauriceButler** [comment]
Nice. :+1: 

Sorry must have missed the previous message in the sea of notifications. 

I could host it somewhere, maybe not a huge urgency now if you are fixing up server.
